### ISSUE TITLE
Read from config file?

### ISSUE THREAD

**Issue by rxaviers** [scottgonzalez/node-git-notifier#6]
Hi @scottgonzalez,

Would you be interested in adding a method to read the bindings and its actions from a config file? For example:

``` javascript
var server = require( "git-notifier" ).createServer();
server.listen( 8000 );
server.load( "./config.yml" )
```

OBS: I've picked yml in this example. But, obviously it could be in whatever format you'd like. The reason I picked yml is that it looks nicer for shell commands:

``` yaml
scottgonzalez/node-git-notifier/heads/master:
  - cd /srv/app.stage
  - git fetch origin
  - echo "Checking out {{commit}}"
  - git checkout --force {{commit}}
  - service app.stage restart

scottgonzalez/node-git-notifier/tags/*:
  - cd /srv/app
  - git fetch origin
  - echo "Checking out {{tag}}"
  - git checkout --force {{tag}}
  - service app restart
```
